version: '3.8'
services:
    db:
        image: test_db
        container_name: testdb_postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test_data